import os
from getpass import getpass
 
ENV_PATH = ".env"
 
# (key, friendly question, is_secret, default)
FIELDS = [
    ("TWILIO_ACCOUNT_SID", "Twilio Account SID (starts with AC)", False, ""),
    ("TWILIO_AUTH_TOKEN", "Twilio Auth Token", True, ""),
    ("TWILIO_WHATSAPP_FROM", "Twilio WhatsApp 'from' number", False, "whatsapp:+14155238886"),
    ("TWILIO_APPROVED_TEMPLATE_SID", "Approved template SID (leave blank for now)", False, ""),
    ("AIRTABLE_TOKEN", "Airtable Personal Access Token (starts with pat)", True, ""),
    ("AIRTABLE_BASE_ID", "Airtable Base ID (starts with app)", False, ""),
    ("AIRTABLE_TABLE", "Airtable table name", False, "Submissions"),
]
 
 
def load_existing():
    """Read the current .env (if any) so we can offer to keep values."""
    values = {}
    if os.path.exists(ENV_PATH):
        with open(ENV_PATH) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    values[k.strip()] = v.strip()
    return values
 
 
def mask(value):
    """Show only the last 4 characters of a saved secret."""
    if not value:
        return "(not set)"
    if len(value) <= 4:
        return "****"
    return "*" * (len(value) - 4) + value[-4:]
 
 
def main():
    print("\n=== WhatsApp bot setup ===")
    print("Press Enter to keep the current value shown in [brackets].\n")
 
    existing = load_existing()
    result = {}
 
    for key, question, is_secret, default in FIELDS:
        current = existing.get(key, default)
        shown = mask(current) if is_secret else (current or "(empty)")
        prompt = f"{question}\n  current: [{shown}]\n  > "
 
        if is_secret:
            # getpass hides typing so your token isn't shown on screen.
            entered = getpass(prompt)
        else:
            entered = input(prompt)
 
        # Keep existing value if they just pressed Enter.
        result[key] = entered.strip() if entered.strip() else current
        print()
 
    # Write everything back to .env
    with open(ENV_PATH, "w") as f:
        f.write("# Generated by setup.py — do not commit this file.\n")
        for key, _, _, _ in FIELDS:
            f.write(f"{key}={result[key]}\n")
 
    print(f"Saved to {os.path.abspath(ENV_PATH)} ✅")
    print("You can run the bot now. Re-run 'python setup.py' any time to change values.")
 
 
if __name__ == "__main__":
    main()   